# Generated by Django 4.2.4 on 2023-09-18 16:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_abbr', models.CharField(max_length=50)),
                ('location_province', models.CharField(max_length=255)),
                ('location_town', models.CharField(max_length=255)),
                ('location_long', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location_lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
            ],
        ),
        migrations.CreateModel(
            name='SamplingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_abbr', models.CharField(max_length=50)),
                ('site_name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='location.location')),
            ],
        ),
        migrations.CreateModel(
            name='SamplingPoint',
            fields=[
                ('point_number', models.AutoField(primary_key=True, serialize=False)),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='location.samplingsite')),
            ],
        ),
    ]
