# Generated by Django 4.2.4 on 2023-09-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SamplingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='location.location')),
            ],
        ),
        migrations.CreateModel(
            name='SamplingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_number', models.IntegerField()),
                ('sampling_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='location.samplingsite')),
            ],
        ),
    ]
