# Generated by Django 4.2.4 on 2023-09-07 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='location_town',
        ),
        migrations.AddField(
            model_name='location',
            name='location_abbr',
            field=models.CharField(default='CL', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='location_lat',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='location_long',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='location_province',
            field=models.CharField(default='CAVINTI', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samplingsite',
            name='site_abbr',
            field=models.CharField(default='CURCC', max_length=50),
            preserve_default=False,
        ),
    ]
