# Generated by Django 4.2.4 on 2025-02-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicercaves', '0002_remove_article_author_id_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
    ]
