# Generated by Django 4.2.4 on 2025-02-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicercaves', '0003_article_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photos',
            field=models.ImageField(upload_to='images/articles/'),
        ),
    ]
