# Generated by Django 4.2.4 on 2025-02-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nicercaves', '0004_alter_article_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photos',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
