# Generated by Django 4.2.4 on 2025-02-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nicercaves', '0005_alter_article_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photos',
        ),
    ]
