# Generated by Django 4.2.4 on 2023-08-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Domain',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.class')),
            ],
            options={
                'verbose_name_plural': 'Genera',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.class')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Phylum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.domain')),
            ],
            options={
                'verbose_name_plural': 'Phyla',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.genus')),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Species_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.species')),
            ],
            options={
                'verbose_name_plural': 'Species_Children',
            },
        ),
        migrations.CreateModel(
            name='Phylum_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phylum_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.class')),
                ('phylum_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.phylum')),
            ],
            options={
                'verbose_name_plural': 'Phylum_Children',
            },
        ),
        migrations.CreateModel(
            name='Order_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.family')),
                ('order_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.order')),
            ],
            options={
                'verbose_name_plural': 'Order_Children',
            },
        ),
        migrations.CreateModel(
            name='Genus_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.species')),
                ('genus_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.genus')),
            ],
            options={
                'verbose_name_plural': 'Genus_Children',
            },
        ),
        migrations.CreateModel(
            name='Family_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.genus')),
                ('family_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.family')),
            ],
            options={
                'verbose_name_plural': 'Family_Children',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.order'),
        ),
        migrations.CreateModel(
            name='Domain_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.phylum')),
                ('domain_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.domain')),
            ],
            options={
                'verbose_name_plural': 'Domain_Children',
            },
        ),
        migrations.CreateModel(
            name='Class_Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.order')),
                ('class_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.class')),
            ],
            options={
                'verbose_name_plural': 'Class_Children',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.phylum'),
        ),
    ]
