# Generated by Django 4.2.4 on 2023-08-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain_child',
            name='domain_child',
        ),
        migrations.RemoveField(
            model_name='domain_child',
            name='domain_parent',
        ),
        migrations.RemoveField(
            model_name='family_child',
            name='family_child',
        ),
        migrations.RemoveField(
            model_name='family_child',
            name='family_parent',
        ),
        migrations.RemoveField(
            model_name='genus_child',
            name='genus_child',
        ),
        migrations.RemoveField(
            model_name='genus_child',
            name='genus_parent',
        ),
        migrations.RemoveField(
            model_name='order_child',
            name='order_child',
        ),
        migrations.RemoveField(
            model_name='order_child',
            name='order_parent',
        ),
        migrations.RemoveField(
            model_name='phylum_child',
            name='phylum_child',
        ),
        migrations.RemoveField(
            model_name='phylum_child',
            name='phylum_parent',
        ),
        migrations.RemoveField(
            model_name='species_child',
            name='species_parent',
        ),
        migrations.AlterField(
            model_name='class',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='taxonomy.phylum'),
        ),
        migrations.AlterField(
            model_name='family',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='taxonomy.order'),
        ),
        migrations.AlterField(
            model_name='genus',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genera', to='taxonomy.class'),
        ),
        migrations.AlterField(
            model_name='order',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='taxonomy.class'),
        ),
        migrations.AlterField(
            model_name='phylum',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phyla', to='taxonomy.domain'),
        ),
        migrations.AlterField(
            model_name='species',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='taxonomy.genus'),
        ),
        migrations.DeleteModel(
            name='Class_Child',
        ),
        migrations.DeleteModel(
            name='Domain_Child',
        ),
        migrations.DeleteModel(
            name='Family_Child',
        ),
        migrations.DeleteModel(
            name='Genus_Child',
        ),
        migrations.DeleteModel(
            name='Order_Child',
        ),
        migrations.DeleteModel(
            name='Phylum_Child',
        ),
        migrations.DeleteModel(
            name='Species_Child',
        ),
    ]
