# Generated by Django 4.2.4 on 2023-09-02 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_remove_domain_child_domain_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kingdoms', to='taxonomy.domain')),
            ],
            options={
                'verbose_name_plural': 'Kingdoms',
            },
        ),
        migrations.AlterField(
            model_name='phylum',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phyla', to='taxonomy.kingdom'),
        ),
    ]
