# Generated by Django 4.2.4 on 2023-09-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_kingdom_alter_phylum_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_domain', models.CharField(max_length=100)),
                ('tax_kingdom', models.CharField(max_length=100)),
                ('tax_phylum', models.CharField(max_length=100)),
                ('tax_class', models.CharField(max_length=100)),
                ('tax_order', models.CharField(max_length=100)),
                ('tax_family', models.CharField(max_length=100)),
                ('tax_genus', models.CharField(max_length=100)),
                ('tax_species', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Taxonomic Classifications',
            },
        ),
    ]
