# Generated by Django 4.2.4 on 2023-09-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolate_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'isolates',
            },
        ),
    ]
