# Generated by Django 4.2.4 on 2023-09-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_type', models.CharField(max_length=50)),
                ('host_species', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=50)),
                ('sample_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='host.host')),
            ],
        ),
    ]
