# Generated by Django 4.2.4 on 2023-09-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='host',
            options={},
        ),
        migrations.RemoveField(
            model_name='host',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='host',
            name='host_taxonomy',
        ),
        migrations.AddField(
            model_name='host',
            name='host_name',
            field=models.CharField(default='BAT', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='host_species',
            field=models.CharField(default='Ptenochirus jagori', max_length=255),
            preserve_default=False,
        ),
    ]
