# Generated by Django 4.2.4 on 2025-02-26 17:17

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlephoto',
            name='photo',
            field=models.ImageField(upload_to=upload.models.get_upload_path),
        ),
    ]
