# Generated by Django 4.2.4 on 2023-09-06 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0004_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strains', to='taxonomy.taxonomy')),
            ],
            options={
                'verbose_name_plural': 'Strains',
            },
        ),
    ]
