# Generated by Django 4.2.4 on 2024-02-19 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_staff",
        ),
    ]
