# Generated by Django 4.2.4 on 2023-09-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=25)),
                ('institution', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('type_id', models.IntegerField(blank=True)),
                ('host_type', models.CharField(blank=True, max_length=25)),
                ('host_species', models.CharField(blank=True, max_length=50)),
                ('sample_type', models.CharField(max_length=25)),
                ('accession_no', models.CharField(blank=True, max_length=100)),
                ('human_readable_id', models.CharField(blank=True, max_length=150)),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='source.project')),
                ('sampling_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='location.samplingpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Isolate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_readable_id', models.CharField(blank=True, max_length=150)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.source')),
            ],
        ),
    ]
