# Generated by Django 4.2.4 on 2023-09-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_collection', models.CharField(max_length=255)),
                ('source_institution', models.CharField(max_length=255)),
                ('type_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bacteria',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='source.source')),
                ('bacteria_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('source.source',),
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='source.source')),
                ('yeast_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('source.source',),
        ),
    ]
