# Generated by Django 4.2.4 on 2024-02-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection", models.CharField(max_length=25)),
                ("institution", models.CharField(max_length=50)),
                ("host_type", models.CharField(blank=True, max_length=25)),
                ("host_species", models.CharField(blank=True, max_length=50)),
                ("sample_type", models.CharField(max_length=25)),
                ("project_name", models.CharField(max_length=50)),
                ("project_abbr", models.CharField(max_length=25)),
                ("loc_location", models.CharField(max_length=50)),
                ("loc_abbr", models.CharField(max_length=25)),
                ("loc_sampling_site", models.CharField(max_length=50)),
                ("loc_site_abbr", models.CharField(max_length=25)),
                ("loc_sampling_point", models.IntegerField(default=0)),
                ("human_readable_id", models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Strain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("human_readable_id", models.CharField(blank=True, max_length=150)),
                ("accession_no", models.CharField(blank=True, max_length=100)),
                ("type", models.IntegerField()),
                ("type_id", models.IntegerField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strains",
                        to="source.source",
                    ),
                ),
            ],
        ),
    ]
