# Generated by Django 4.2.4 on 2023-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abbr',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
