# Generated by Django 4.2.4 on 2023-09-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='source',
            name='type_id',
            field=models.IntegerField(blank=True),
        ),
    ]
