# Generated by Django 4.2.4 on 2024-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strain",
            name="culture_growth",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="strain",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="strain",
            name="morphology",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="strain",
            name="physiology_metabolism",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="strain",
            name="safety_information",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="strain",
            name="sequence_information",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="strain",
            name="taxonomy",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
