# Generated by Django 4.2.4 on 2023-09-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='source.source')),
                ('mold_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('source.source',),
        ),
    ]
