# Generated by Django 4.2.4 on 2024-03-14 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("source", "0002_strain_culture_growth_strain_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Isolate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("human_readable_id", models.CharField(blank=True, max_length=150)),
                ("accession_no", models.CharField(blank=True, max_length=100)),
                ("type", models.IntegerField()),
                ("type_id", models.IntegerField(blank=True)),
                ("description", models.CharField(blank=True, max_length=1000)),
                ("taxonomy", models.JSONField(blank=True, default=dict)),
                ("morphology", models.JSONField(blank=True, default=dict)),
                ("culture_growth", models.JSONField(blank=True, default=dict)),
                ("physiology_metabolism", models.JSONField(blank=True, default=dict)),
                ("safety_information", models.JSONField(blank=True, default=dict)),
                ("sequence_information", models.JSONField(blank=True, default=dict)),
                ("visibility", models.CharField(max_length=20)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isolates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="isolates",
                        to="source.source",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Strain",
        ),
    ]
