# Generated by Django 4.2.4 on 2023-09-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_mold'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='project',
            field=models.CharField(default='DOST NICER CAVES', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='type_id',
            field=models.IntegerField(blank=True),
        ),
    ]
