# Generated by Django 4.2.4 on 2023-11-25 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_remove_source_accession_no_remove_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_readable_id', models.CharField(blank=True, max_length=150)),
                ('accession_no', models.CharField(blank=True, max_length=100)),
                ('type', models.IntegerField()),
                ('type_id', models.IntegerField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strains', to='source.source')),
            ],
        ),
        migrations.DeleteModel(
            name='Isolate',
        ),
    ]
