# Generated by Django 4.2.4 on 2023-09-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0003_source_project_alter_source_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='project',
            new_name='source_project',
        ),
    ]
