# Generated by Django 4.2.4 on 2024-03-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0003_isolate_delete_strain"),
    ]

    operations = [
        migrations.AddField(
            model_name="isolate",
            name="author",
            field=models.CharField(default="A", max_length=150),
            preserve_default=False,
        ),
    ]
