# Generated by Django 4.2.4 on 2023-09-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_rename_project_source_source_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='accession_no',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
