# Generated by Django 4.2.4 on 2024-05-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0004_isolate_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="raw_human_readable_id",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
