# Generated by Django 4.2.4 on 2023-11-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_strain_delete_isolate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='project',
        ),
        migrations.AddField(
            model_name='source',
            name='project_abbr',
            field=models.CharField(default='CAV', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='project_name',
            field=models.CharField(default='NICER CAVES Project', max_length=50),
            preserve_default=False,
        ),
    ]
