# Generated by Django 4.2.4 on 2024-05-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0005_source_raw_human_readable_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="institution",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="source",
            name="project_name",
            field=models.CharField(max_length=150),
        ),
    ]
