# Generated by Django 4.2.4 on 2024-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0006_delete_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="loc_abbr",
            field=models.CharField(default="CAV", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="loc_location",
            field=models.CharField(default="Cavinti", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="loc_sampling_point",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="loc_sampling_site",
            field=models.CharField(
                default="Cavinti Underground River and Caves Complex", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="loc_site_abbr",
            field=models.CharField(default="CURCC", max_length=25),
            preserve_default=False,
        ),
    ]
