# Generated by Django 4.2.4 on 2024-05-06 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("source", "0006_alter_source_institution_alter_source_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="author",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="author_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
