# Generated by Django 4.2.4 on 2024-02-27 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0007_source_loc_abbr_source_loc_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="sampling_point",
        ),
    ]
