# Generated by Django 4.2.4 on 2024-05-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0007_source_author_source_author_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="isolate",
            name="type_id",
        ),
        migrations.AddField(
            model_name="isolate",
            name="raw_accession_no",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
