# Generated by Django 4.2.4 on 2024-05-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0008_remove_isolate_type_id_isolate_raw_accession_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="isolate",
            name="type_id",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
