# Generated by Django 4.2.4 on 2024-05-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0009_isolate_type_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="collection_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="source",
            name="institution_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="source",
            name="institution",
            field=models.CharField(max_length=25),
        ),
    ]
