# Generated by Django 4.2.4 on 2024-11-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0013_alter_source_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="loc_city",
            field=models.CharField(default="Cavinti", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="source",
            name="loc_province",
            field=models.CharField(default="Laguna", max_length=50),
            preserve_default=False,
        ),
    ]
