# Generated by Django 4.2.4 on 2024-11-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0014_source_loc_city_source_loc_province"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="source",
            name="loc_location",
        ),
        migrations.AddField(
            model_name="source",
            name="loc_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=22, null=True
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="loc_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=16, max_digits=22, null=True
            ),
        ),
    ]
