# Generated by Django 4.2.4 on 2024-12-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0016_source_miso_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="miso_categories_string",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
