# Generated by Django 4.2.4 on 2024-12-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("source", "0017_source_miso_categories_string"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessionCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_accession_no", models.CharField(blank=True, max_length=100)),
                ("count", models.IntegerField(default=0)),
            ],
        ),
    ]
